const adjectives: string[] = [
  'able', 'active', 'actual', 'agile', 'airy', 'alert', 'alive', 'ample', 'ancient', 'angular',
  'apt', 'ardent', 'arid', 'artful', 'astute', 'avid', 'azure', 'balmy', 'bare', 'barren',
  'bashful', 'blithe', 'bold', 'bountiful', 'brave', 'breezy', 'bright', 'brisk', 'broad', 'buoyant',
  'calm', 'candid', 'capable', 'careful', 'casual', 'cheerful', 'clean', 'clear', 'clever', 'close',
  'cloudy', 'coastal', 'cozy', 'crisp', 'curious', 'dainty', 'daring', 'dark', 'dashing', 'dauntless',
  'deep', 'devout', 'dew', 'distant', 'diverse', 'divine', 'docile', 'durable', 'dynamic', 'eager',
  'earnest', 'easy', 'elegant', 'empty', 'enchanted', 'endless', 'epic', 'even', 'faithful', 'fancy',
  'far', 'fast', 'fertile', 'fierce', 'fine', 'firm', 'flat', 'fleet', 'flowing', 'fluent',
  'flying', 'fond', 'forested', 'free', 'fresh', 'full', 'fun', 'gallant', 'gentle', 'glad',
  'gleaming', 'glowing', 'graceful', 'grand', 'green', 'grounded', 'happy', 'hardy', 'harmless', 'hazy',
  'hidden', 'high', 'honest', 'humble', 'icy', 'idle', 'inland', 'innocent', 'intrepid', 'inventive',
  'joyful', 'jovial', 'keen', 'kind', 'large', 'lazy', 'lean', 'light', 'lively', 'long',
  'loud', 'low', 'loyal', 'lucky', 'lush', 'magical', 'majestic', 'mild', 'misty', 'mobile',
  'modest', 'moist', 'mossy', 'moving', 'muted', 'narrow', 'native', 'natural', 'neat', 'nimble',
  'noble', 'obscure', 'odd', 'open', 'orderly', 'outer', 'peaceful', 'plain', 'playful', 'plucky',
  'polar', 'polite', 'prompt', 'proper', 'pure', 'quick', 'quiet', 'radiant', 'rapid', 'rare',
  'ready', 'real', 'remote', 'resilient', 'rich', 'robust', 'rocky', 'rosy', 'round', 'rugged',
  'rustic', 'safe', 'sandy', 'sapphire', 'scenic', 'serene', 'sharp', 'shining', 'silent', 'silvery',
  'simple', 'sleek', 'slim', 'slow', 'smooth', 'soft', 'solid', 'solitary', 'sparse', 'spirited',
  'spring', 'steady', 'still', 'stoic', 'stout', 'strong', 'sturdy', 'subtle', 'sunny', 'supple',
  'swift', 'tender', 'thick', 'thin', 'tidy', 'tiny', 'tireless', 'tranquil', 'tropical', 'true',
  'twilight', 'unique', 'upbeat', 'valiant', 'vast', 'vibrant', 'vivid', 'warm', 'wild', 'windy',
  'wiry', 'wise', 'wonderful', 'woody', 'young', 'zealous', 'zesty', 'amber', 'amiable', 'ancient',
  'assured', 'balanced', 'bounteous', 'brilliant', 'bronze', 'calm', 'careful', 'celestial', 'central',
  'charming', 'classic', 'coastal', 'coherent', 'complete', 'concise', 'cool', 'cordial', 'creative',
  'crimson', 'crisp', 'crystal', 'daily', 'decent', 'decisive', 'devoted', 'digital', 'diligent',
  'direct', 'distinct', 'durable', 'earnest', 'earthy', 'effortless', 'endless', 'enduring', 'eternal',
  'even', 'exact', 'faithful', 'familiar', 'famous', 'focused', 'formidable', 'forward', 'frank',
  'friendly', 'frugal', 'general', 'genuine', 'gracious', 'grateful', 'hearty', 'helpful', 'hopeful',
  'ideal', 'immense', 'impeccable', 'ingenious', 'integral', 'jovial', 'joyous', 'jubilant', 'just',
  'kindly', 'knowing', 'leading', 'lofty', 'logical', 'lasting', 'legendary', 'limitless', 'luminous',
  'masterful', 'meaningful', 'mellow', 'mindful', 'modern', 'natural', 'nifty', 'noble', 'noted',
  'optimum', 'organic', 'original', 'outstanding', 'patient', 'peaceful', 'perennial', 'perfect',
  'pioneering', 'placid', 'pleasant', 'polished', 'positive', 'potent', 'practical', 'precise', 'primal',
  'pristine', 'profound', 'refreshing', 'regal', 'remarkable', 'renewed', 'resolute', 'resourceful',
  'restful', 'reverent', 'rhythmic', 'roaming', 'rolling', 'sacred', 'sage', 'sane', 'savvy',
  'seasonal', 'secure', 'self', 'sensible', 'sharp', 'sincere', 'skillful', 'smart', 'soaring',
  'sovereign', 'stable', 'stellar', 'strategic', 'sublime', 'sustained', 'thoughtful', 'thriving',
  'timeless', 'tolerant', 'trusting', 'trusted', 'ultimate', 'unbeaten', 'unbound', 'undaunted',
  'unfailing', 'unfolding', 'upright', 'urban', 'useful', 'verdant', 'versatile', 'vigilant',
  'vital', 'wary', 'watchful', 'welcoming', 'wholesome', 'witty', 'wondrous', 'worthy', 'youthful',
  'afoot', 'airborne', 'aloft', 'amber', 'apt', 'athletic', 'attentive', 'balanced', 'bearing',
  'blooming', 'blissful', 'boreal', 'boundless', 'breezy', 'buoyant', 'ceaseless', 'centered',
  'certain', 'changeless', 'cherished', 'civic', 'civil', 'clear', 'cognizant', 'collected',
  'committed', 'common', 'composed', 'confident', 'conscious', 'consistent', 'content', 'controlled',
  'core', 'cordial', 'cosmic', 'crafted', 'custom', 'deft', 'delicate', 'deliberate', 'dependable',
  'dexterous', 'durable', 'eager', 'earnest', 'efficient', 'elastic', 'elevated', 'emerald',
  'empowered', 'energetic', 'enhanced', 'equal', 'equitable', 'established', 'evergreen', 'exact',
  'expansive', 'expert', 'extra', 'fabled', 'farsighted', 'fearless', 'flexible', 'frosty',
  'fluid', 'focused', 'fortunate', 'free', 'fresh', 'fulfilling', 'fundamental', 'glorious',
  'golden', 'graceful', 'great', 'groundbreaking', 'hallowed', 'harmonious', 'healthy', 'hearty',
  'honest', 'inventive', 'invincible', 'joyous', 'justified', 'keen', 'laudable', 'lavish', 'lawful',
  'lithe', 'logical', 'long', 'luminous', 'lyrical', 'magnetic', 'manifest', 'notable', 'nurturing',
  'objective', 'observant', 'obvious', 'omnipresent', 'ongoing', 'open', 'optimal', 'orderly',
  'original', 'overarching', 'panoramic', 'paramount', 'particular', 'patient', 'peerless', 'perceptive',
  'permanent', 'persistent', 'philosophical', 'pioneering', 'playful', 'purposeful', 'real', 'reasoned',
  'refined', 'regenerative', 'regulated', 'reliant', 'renowned', 'resilient', 'responsive', 'right',
  'rigorous', 'robust', 'rooted', 'sagacious', 'saintly', 'serene', 'settled', 'shared', 'singular',
  'skilled', 'smooth', 'sober', 'social', 'solid', 'sound', 'spacious', 'splendid', 'stalwart',
  'steadfast', 'stoic', 'strident', 'strong', 'studious', 'supple', 'tenacious', 'thankful',
  'thorough', 'tidy', 'tirelessly', 'tranquil', 'true', 'truehearted', 'unerring', 'unified',
  'universal', 'unshaken', 'upstanding', 'valorous', 'venerable', 'vibrant', 'victorious',
  'wholehearted', 'willing', 'winsome', 'worldly', 'yearning', 'yielding',
  'abiding', 'accomplished', 'adept', 'admirable', 'adroit', 'affable', 'affirmative', 'ageless',
  'agreeable', 'altruistic', 'ambitious', 'amicable', 'approachable', 'arcadian', 'auspicious',
  'benevolent', 'benign', 'brazen', 'bracing', 'blazing', 'coastal', 'collaborative', 'communal',
  'companionable', 'compassionate', 'compatible', 'congenial', 'cooperative', 'courageous', 'credible',
  'cultivated', 'dapper', 'daring', 'dauntless', 'diligent', 'discerning', 'distinguished', 'dynamic',
  'edifying', 'efficient', 'empathic', 'enterprising', 'enthusiastic', 'equable', 'exceptional',
  'exuberant', 'fair', 'faithful', 'favorable', 'fearless', 'felicitous', 'fitting', 'flourishing',
  'forgiving', 'forthright', 'foster', 'free', 'fresh', 'friendly', 'gallant', 'genuine', 'gifted',
  'giving', 'good', 'graceful', 'gracious', 'great', 'grounded', 'growing', 'guided', 'hardworking',
  'harmonious', 'hearty', 'helpful', 'heroic', 'high', 'honest', 'honorable', 'hopeful', 'humble',
  'idealistic', 'imaginative', 'impartial', 'inclusive', 'industrious', 'innovative', 'insightful',
  'inspiring', 'integrous', 'intentional', 'justice', 'knowing', 'knowledgeable', 'leading', 'learned',
  'light', 'loving', 'magnanimous', 'measured', 'mindful', 'moderate', 'motivated', 'moving',
  'noble', 'nourishing', 'objective', 'open', 'outstanding', 'patient', 'perceptive', 'persevering',
  'philanthropic', 'practical', 'principled', 'proactive', 'productive', 'progressive', 'prudent',
  'qualified', 'rational', 'receptive', 'reflective', 'reliable', 'responsive', 'righteous', 'secure',
  'sensitive', 'serene', 'service', 'spirited', 'steadfast', 'supportive', 'sweet', 'sympathetic',
  'talented', 'temperate', 'thankful', 'thoughtful', 'tolerant', 'transparent', 'trusting', 'virtuous',
  'visionary', 'warmhearted', 'well', 'willing', 'wise', 'worthy',
];

export default adjectives;
